;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	beginning-of-buffer
	c-electric-star
	end-of-visual-line
	org-self-insert-command
	))

(setq mc/cmds-to-run-once
      '(
	))
