;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	hydra-multiple-cursors/mc/edit-lines
	org-delete-char
	org-self-insert-command
	))

(setq mc/cmds-to-run-once
      '(
	))
