version: 2
updates:
  # Update helix-editor
  - package-ecosystem: gitsubmodule
    directory: /
    allow:
      - dependency-name: helix
    schedule:
      interval: daily
      # UTC
      time: "08:00"
    reviewers:
      - ericcrosson
    labels:
      - dependencies
      - git
      - helix
    open-pull-requests-limit: 3
