{pkgs}: let
  dispatch = ../profiles/eric/modules/git-hook-dispatch.sh;
  gitModule = ../profiles/eric/modules/git.nix;
in
  pkgs.runCommand "git-hook-dispatch-test" {
    nativeBuildInputs = [
      pkgs.git
      pkgs.coreutils
      pkgs.gnugrep
    ];
  } ''
    set -eu

    base=$PWD
    export HOME="$base/home"
    mkdir -p "$HOME" "$base/repos" "$base/stubs"
    BASE_PATH="$PATH"

    fail() { echo "FAIL: $*" >&2; exit 1; }
    assert_contains() { grep -qF -- "$2" "$1" || fail "expected '$2' in $1"; }

    # --- hook dispatch fixtures ---------------------------------------
    mkdir -p "$base/hooks"
    cp ${dispatch} "$base/hooks/dispatch.sh"
    ln -sf dispatch.sh "$base/hooks/pre-commit"
    ln -sf dispatch.sh "$base/hooks/pre-push"
    chmod +x "$base/hooks/dispatch.sh"

    # Runner stubs record argv and env; nix stub acts per NIX_BEHAVIOR
    # (ok = write config, fail = broken eval, noconfig = nothing).
    cat > "$base/stubs/prek" <<'STUB'
    #!/bin/sh
    printf 'prek %s\n' "$*" >> "$STUB_LOG"
    env | grep -E '^(GIT_|PREK_)' | sort >> "$STUB_LOG"
    exit 0
    STUB
    cat > "$base/stubs/pre-commit" <<'STUB'
    #!/bin/sh
    printf 'pre-commit %s\n' "$*" >> "$STUB_LOG"
    env | grep -E '^(GIT_|PREK_)' | sort >> "$STUB_LOG"
    exit 0
    STUB
    cat > "$base/stubs/nix" <<'STUB'
    #!/bin/sh
    printf 'nix %s\n' "$*" >> "$NIX_LOG"
    if [ "''${NIX_BEHAVIOR:-ok}" = ok ]; then
      touch .pre-commit-config.yaml
      exit 0
    fi
    if [ "''${NIX_BEHAVIOR:-ok}" = fail ]; then
      exit 1
    fi
    exit 0
    STUB
    chmod +x "$base/stubs/prek" "$base/stubs/pre-commit" "$base/stubs/nix"

    mkrepo() { # name flake|plain config|none shim|none|prek|precommit|legacy marker
      d="$base/repos/$1"
      mkdir -p "$d"
      (cd "$d" && git init -qb main >/dev/null 2>&1)
      if [ "$2" = flake ]; then
        touch "$d/flake.nix"
        if [ "''${5:-}" = marker ]; then printf '# git-hooks integration\n' > "$d/flake.nix"; fi
      fi
      if [ "$3" = config ]; then printf 'repos: []\n' > "$d/.pre-commit-config.yaml"; fi
      case "$4" in
        prek) printf '#!/bin/sh\n# generated by prek\n' > "$d/.git/hooks/pre-commit" ;;
        precommit) printf '#!/bin/sh\n# File generated by pre-commit\n' > "$d/.git/hooks/pre-commit" ;;
        legacy)
          printf '#!/bin/sh\necho legacy-ran >> "$LEGACY_LOG"\n' > "$d/.git/hooks/pre-commit"
          chmod +x "$d/.git/hooks/pre-commit"
          ;;
      esac
    }

    # invoke <repo> <hook> <stubdir> VAR=val... : run dispatcher in repo
    # with a scrubbed env (stub dir first on PATH).
    invoke() {
      repo_dir="$base/repos/$1"
      shift
      hook_name="$1"
      shift
      stub_dir="$1"
      shift
      (
        cd "$repo_dir"
        env -i PATH="$stub_dir:$BASE_PATH" HOME="$HOME" "$@" \
          "$base/hooks/$hook_name" -- the -- args
      )
    }

    # --- 1. fast path: config present, no shim -> prek with exact argv ---
    mkrepo fast plain config none
    if ! invoke fast pre-commit "$base/stubs" STUB_LOG="$base/log1" NIX_LOG="$base/plog1"; then
      fail "fast path exited nonzero"
    fi
    assert_contains "$base/log1" "prek hook-impl --hook-type=pre-commit --config=.pre-commit-config.yaml --hook-dir $base/repos/fast/.git/hooks -- -- the -- args"
    [ -f "$base/plog1" ] && fail "fast path invoked nix"

    # --- 2. runner detection: pre-commit shim -> pre-commit runner ---
    mkrepo detpc plain config precommit
    invoke detpc pre-commit "$base/stubs" STUB_LOG="$base/log2" \
      || fail "pre-commit runner path exited nonzero"
    head -1 "$base/log2" | grep -q '^pre-commit hook-impl' \
      || fail "expected pre-commit runner, got: $(head -1 "$base/log2")"

    # --- 3. runner detection: prek-marked shim -> prek runner ---
    mkrepo detprek plain config prek
    invoke detprek pre-commit "$base/stubs" STUB_LOG="$base/log3" \
      || fail "prek shim path exited nonzero"
    head -1 "$base/log3" | grep -q '^prek hook-impl' \
      || fail "expected prek runner, got: $(head -1 "$base/log3")"

    # --- 4. fail closed: runner missing -> exit 1 ------------------------
    mkrepo norunner plain config precommit
    if invoke norunner pre-commit /usr/bin >"$base/out4" 2>"$base/err4"; then
      fail "missing runner should fail closed"
    fi
    grep -q 'not found' "$base/err4" || fail "missing-runner message missing: $(cat "$base/err4")"

    # --- 5. fail closed: nix develop fails -> exit 1 ----------------------
    mkrepo badflake flake none none marker
    if invoke badflake pre-commit "$base/stubs" NIX_BEHAVIOR=fail \
        STUB_LOG="$base/log5" NIX_LOG="$base/plog5" >"$base/out5" 2>"$base/err5"; then
      fail "broken nix develop should fail closed"
    fi
    grep -q 'nix develop failed' "$base/err5" \
      || fail "nix-failure message missing: $(cat "$base/err5")"

    # --- 6. cold path: nix develop generates config, then prek runs --------
    mkrepo cold flake none none marker
    (cd "$base/repos/cold" && git config core.hooksPath "$base/hooks")
    invoke cold pre-commit "$base/stubs" NIX_BEHAVIOR=ok \
      STUB_LOG="$base/log6" NIX_LOG="$base/plog6" \
      || fail "cold path exited nonzero"
    assert_contains "$base/plog6" "nix develop --no-update-lock-file -c true"
    assert_contains "$base/log6" "prek hook-impl --hook-type=pre-commit"
    [ -f "$base/repos/cold/.pre-commit-config.yaml" ] \
      || fail "cold path did not produce config in repo"

    if (cd "$base/repos/cold" && git config --local --get core.hooksPath >/dev/null 2>&1); then
      fail "cold path left a repo-local hooksPath override"
    fi
    # --- 7. skip loudly: flake, devShell declares no hooks -> exit 0 --------
    # Ordinary flakes without hook integration must not invoke nix develop;
    # test fixtures commonly contain intentionally non-evaluable flake.nix.
    mkrepo ordinaryflake flake none none
    invoke ordinaryflake pre-commit "$base/stubs" STUB_LOG="$base/log-ordinary" NIX_LOG="$base/plog-ordinary" \
      >"$base/out-ordinary" 2>"$base/err-ordinary" \
      || fail "ordinary flake should skip without nix"
    [ ! -f "$base/plog-ordinary" ] || fail "ordinary flake invoked nix develop"
    grep -q 'devShell declares no pre-commit hooks' "$base/err-ordinary" \
      || fail "ordinary-flake skip message missing"
    mkrepo flakelegacy flake none legacy
    invoke flakelegacy pre-commit "$base/stubs" STUB_LOG="$base/log-flakelegacy" \
      LEGACY_LOG="$base/legacy-flake" || fail "flake legacy hook should run"
    [ -f "$base/legacy-flake" ] && grep -q 'legacy-ran' "$base/legacy-flake" \
      || fail "flake legacy hook did not run"


    # Hook-enabled flake whose shellHook produces no config must skip loudly.
    mkrepo nohooks flake none none marker
    invoke nohooks pre-commit "$base/stubs" NIX_BEHAVIOR=noconfig \
      STUB_LOG="$base/log7" NIX_LOG="$base/plog7" >"$base/out7" 2>"$base/err7" \
      || fail "no-hooks repo should exit 0"
    grep -q 'devShell declares no pre-commit hooks' "$base/err7" \
      || fail "no-hooks message missing: $(cat "$base/err7")"
    [ -f "$base/plog7" ] || fail "nix stub not invoked for flake repo"

    # --- 8. legacy fallback: hand-written hook runs -------------------------
    mkrepo legacy plain none legacy
    invoke legacy pre-commit "$base/stubs" STUB_LOG="$base/log8" \
      LEGACY_LOG="$base/legacy8" || fail "legacy fallback exited nonzero"
    [ -f "$base/legacy8" ] && grep -q 'legacy-ran' "$base/legacy8" \
      || fail "legacy hook did not run"

    # --- 9. runner shims not double-dispatched via legacy path --------------
    for kind in prek precommit; do
      mkrepo "shim-$kind" plain none "$kind"
      invoke "shim-$kind" pre-commit "$base/stubs" STUB_LOG="$base/log9-$kind" \
        LEGACY_LOG="$base/legacy9-$kind" || fail "shim-$kind repo should exit 0"
      [ -f "$base/legacy9-$kind" ] && fail "shim-$kind was executed as legacy hook"
    done

    # --- 10. env hygiene: repo-targeting GIT_* and escape hatch stripped ----
    mkrepo envtest plain config none
    invoke envtest pre-commit "$base/stubs" STUB_LOG="$base/log10" \
      GIT_DIR=poison GIT_WORK_TREE=poison GIT_INDEX_FILE=poison \
      GIT_OBJECT_DIRECTORY=poison GIT_ALTERNATE_OBJECT_DIRECTORIES=poison \
      GIT_COMMON_DIR=poison GIT_GRAFT_FILE=poison GIT_CONFIG=poison \
      GIT_CONFIG_PARAMETERS=poison GIT_QUARANTINE_PATH=poison \
      PREK_ALLOW_NO_CONFIG=1 || fail "env hygiene scenario exited nonzero"
    for v in GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE GIT_OBJECT_DIRECTORY \
      GIT_ALTERNATE_OBJECT_DIRECTORIES GIT_COMMON_DIR GIT_GRAFT_FILE \
      GIT_CONFIG GIT_CONFIG_PARAMETERS GIT_QUARANTINE_PATH PREK_ALLOW_NO_CONFIG; do
      grep -q "^$v=" "$base/log10" && fail "env var $v leaked into runner"
    done

    # --- 11. stage derivation: pre-push hook -> --hook-type=pre-push --------
    mkrepo pushtest plain config none
    (
      cd "$base/repos/pushtest"
      printf 'refs/heads/main refs/heads/main 0000000000000000000000000000000000000000 abcdef\n' \
        | env -i PATH="$base/stubs:$BASE_PATH" HOME="$HOME" STUB_LOG="$base/log11" \
          "$base/hooks/pre-push" origin https://example.invalid/repo.git
    ) || fail "pre-push scenario exited nonzero"
    assert_contains "$base/log11" "prek hook-impl --hook-type=pre-push --config=.pre-commit-config.yaml"
    # --- 12. home-manager wiring keeps both stages on this dispatcher ------
    assert_contains ${gitModule} 'hookDispatch = pkgs.writeShellScript "git-hook-dispatch"'
    assert_contains ${gitModule} 'pre-commit = hookDispatch;'
    assert_contains ${gitModule} 'pre-push = hookDispatch;'


    touch "$out"
  ''
