---
name: Update nix flake input

inputs:
  flake-input:
    description: The name of the flake input to update
    required: true
    type: string

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - uses: DeterminateSystems/nix-installer-action@main

    - name: Update ${{ inputs.flake-input }} flake input
      uses: DeterminateSystems/update-flake-lock@v16
      with:
        commit-msg: "chore(nix): update ${{ inputs.flake-input }} flake input"
        inputs: ${{ inputs.flake-input }}
        git-author-name: github-actions
        git-author-email: action@github.com
        git-committer-name: github-actions
        git-committer-email: action@github.com
        pr-assignees: EricCrosson
        pr-title: Update ${{ inputs.flake-input }} flake input
        pr-labels: |
          dependencies
          nix
          ${{ inputs.flake-input }}
        token: ${{ secrets.GH_TOKEN_PR }}
