theme = "spacebones_light"

[keys.normal]
# "space" = {f = {d = ":w"}}
# "space" = {e = "file_picker"}
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"

"space" = {t = ":tree-sitter-subtree"}

[editor]
idle-timeout = 0

# Introduced in https://github.com/helix-editor/helix/pull/1154
[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"
