#!/bin/sh
# Global git hook dispatcher: makes pre-commit-style hooks work in every
# worktree and fresh clone, regardless of which checkout generated the hook
# config or which runner installed it.
#
# Stages: link or copy this script to pre-commit / pre-push; the stage is
# derived from the invoked name (home-manager's programs.git.hooks does this
# via its linkFarm).
#
# Policy:
#   - Repo with .pre-commit-config.yaml      -> run the config through the
#     runner the repo's hooks were installed with (prek or pre-commit),
#     detected from the shim in the common hooks dir.
#   - Flake repo without the config          -> one `nix develop` eval so the
#     devShell's git-hooks.nix shellHook symlinks the config into THIS
#     worktree, then run as above (hook entries carry absolute store paths,
#     so the devShell env is not needed).
#   - Flake repo whose devShell declares no hooks -> skip loudly (exit 0).
#   - Failed nix develop eval (broken flake, network) -> FAIL CLOSED.
#   - Non-flake repo without config          -> honor a legacy hook script in
#     .git/hooks if one exists (runner shims excluded; a global
#     core.hooksPath would otherwise silently disable them).
#
# The only sanctioned bypass is `git commit|push --no-verify`.

unset PREK_ALLOW_NO_CONFIG

# git exports repo-targeting GIT_* variables to hooks (notably GIT_DIR and
# GIT_INDEX_FILE in linked worktrees). prek and pre-commit pass them
# through, and they hijack nested git operations in hook subprocesses (e.g.
# tests that commit in temp repos operate on THIS repo instead). Hooks run
# with cwd at the repo root, so these variables are redundant; drop them.
unset GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE GIT_OBJECT_DIRECTORY \
      GIT_ALTERNATE_OBJECT_DIRECTORIES GIT_COMMON_DIR GIT_GRAFT_FILE \
      GIT_CONFIG GIT_CONFIG_PARAMETERS GIT_QUARANTINE_PATH

STAGE="$(basename "$0")"

REPO="$(git rev-parse --show-toplevel 2>/dev/null)" || exit 0
cd "$REPO" || exit 1
COMMON="$(git rev-parse --path-format=absolute --git-common-dir 2>/dev/null)" || exit 1
SHIM="$COMMON/hooks/$STAGE"

# Detect the runner from the shim the repo's hooks were installed with.
# prek marks its shims; Python pre-commit installs a tiny python launcher.
# Default to prek when no shim is present.
RUNNER="prek"
if [ -f "$SHIM" ] && grep -Eq 'pre_commit|pre-commit' "$SHIM" 2>/dev/null \
    && ! grep -q 'generated by prek' "$SHIM" 2>/dev/null; then
    RUNNER="pre-commit"
fi

resolve_runner() {
    RUNNER_BIN="${RUNNER}"
    command -v "$RUNNER_BIN" >/dev/null 2>&1 && return 0
    if [ "$RUNNER" = "prek" ]; then
        for cand in "/etc/profiles/per-user/$(id -un)/bin/prek" \
                    "/run/current-system/sw/bin/prek" \
                    "$HOME/.nix-profile/bin/prek"; do
            if [ -x "$cand" ]; then RUNNER_BIN="$cand"; return 0; fi
        done
    else
        for cand in "/etc/profiles/per-user/$(id -un)/bin/pre-commit" \
                    "/run/current-system/sw/bin/pre-commit" \
                    "$HOME/.nix-profile/bin/pre-commit"; do
            if [ -x "$cand" ]; then RUNNER_BIN="$cand"; return 0; fi
        done
    fi
    return 1
}

resolve_runner || {
    printf 'hook dispatcher: %s not found; refusing to bypass hooks (use --no-verify)\n' "$RUNNER" >&2
    exit 1
}
run_hooks() {
    exec "$RUNNER_BIN" hook-impl --hook-type="$STAGE" --config=.pre-commit-config.yaml --hook-dir "$COMMON/hooks" -- "$@"
}

CONFIG="$REPO/.pre-commit-config.yaml"

if [ -f "$CONFIG" ]; then
    run_hooks "$@"
fi

if [ -f "$REPO/flake.nix" ]; then
    if ! nix develop --no-update-lock-file -c true; then
        printf 'hook dispatcher: nix develop failed; blocking %s (bypass with --no-verify)\n' "$STAGE" >&2
        exit 1
    fi
    # The devShell may have (re)installed shims; re-detect the runner.
    if [ -f "$SHIM" ] && grep -Eq 'pre_commit|pre-commit' "$SHIM" 2>/dev/null \
        && ! grep -q 'generated by prek' "$SHIM" 2>/dev/null; then
        RUNNER="pre-commit"
    else
        RUNNER="prek"
    fi
    if resolve_runner; then
        if [ -f "$CONFIG" ]; then
            run_hooks "$@"
        fi
    fi
    printf 'hook dispatcher: devShell declares no pre-commit hooks; skipping %s\n' "$STAGE" >&2
    exit 0
fi

# Legacy fallback: repos with hand-installed hook scripts. Runner shims are
# excluded so we never double-dispatch through a dead shim.
if [ -f "$SHIM" ] \
    && ! grep -q 'generated by prek' "$SHIM" 2>/dev/null \
    && ! grep -Eq 'pre_commit|pre-commit' "$SHIM" 2>/dev/null; then
    exec "$SHIM" "$@"
fi

exit 0
