#!/bin/sh
# Global git hook dispatcher: makes pre-commit-style hooks work in every
# worktree and fresh clone, regardless of which checkout generated the hook
# config or which runner installed it.
#
# Stages: link or copy this script to pre-commit / pre-push; the stage is
# derived from the invoked name (home-manager's programs.git.hooks does this
# via its linkFarm).
#
# Policy:
#   - Repo with .pre-commit-config.yaml      -> run the config through the
#     runner the repo's hooks were installed with (prek or pre-commit),
#     detected from the shim in the common hooks dir.
#   - Flake repo missing the config or its shims -> one `nix develop` eval so
#     the devShell's git-hooks.nix shellHook installs both into THIS worktree,
#     then run as above (hook entries carry absolute store paths, so the
#     devShell env is not needed). The eval masks the global core.hooksPath:
#     pre-commit's installer refuses while any core.hooksPath is visible.
#   - Flake repo whose devShell declares no hooks -> skip loudly (exit 0).
#   - Failed nix develop eval (broken flake, network) -> FAIL CLOSED.
#   - Non-flake repo without config          -> honor a legacy hook script in
#     .git/hooks if one exists (runner shims excluded; a global
#     core.hooksPath would otherwise silently disable them).
#
# The only sanctioned bypass is `git commit|push --no-verify`.

unset PREK_ALLOW_NO_CONFIG

# git exports repo-targeting GIT_* variables to hooks (notably GIT_DIR and
# GIT_INDEX_FILE in linked worktrees). prek and pre-commit pass them
# through, and they hijack nested git operations in hook subprocesses (e.g.
# tests that commit in temp repos operate on THIS repo instead). Hooks run
# with cwd at the repo root, so these variables are redundant; drop them.
unset GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE GIT_OBJECT_DIRECTORY \
      GIT_ALTERNATE_OBJECT_DIRECTORIES GIT_COMMON_DIR GIT_GRAFT_FILE \
      GIT_CONFIG GIT_CONFIG_PARAMETERS GIT_QUARANTINE_PATH

STAGE="$(basename "$0")"

REPO="$(git rev-parse --show-toplevel 2>/dev/null)" || exit 0
cd "$REPO" || exit 1
COMMON="$(git rev-parse --path-format=absolute --git-common-dir 2>/dev/null)" || exit 1
SHIM="$COMMON/hooks/$STAGE"

# Detect the runner from the shim the repo's hooks were installed with.
# prek marks its shims; Python pre-commit installs a tiny python launcher.
# Default to prek when no shim is present.
RUNNER="prek"
if [ -f "$SHIM" ] && grep -Eq 'pre_commit|pre-commit' "$SHIM" 2>/dev/null \
    && ! grep -q 'generated by prek' "$SHIM" 2>/dev/null; then
    RUNNER="pre-commit"
fi

resolve_runner() {
    RUNNER_BIN="${RUNNER}"
    command -v "$RUNNER_BIN" >/dev/null 2>&1 && return 0
    if [ "$RUNNER" = "prek" ]; then
        for cand in "/etc/profiles/per-user/$(id -un)/bin/prek" \
                    "/run/current-system/sw/bin/prek" \
                    "$HOME/.nix-profile/bin/prek"; do
            if [ -x "$cand" ]; then RUNNER_BIN="$cand"; return 0; fi
        done
    else
        for cand in "/etc/profiles/per-user/$(id -un)/bin/pre-commit" \
                    "/run/current-system/sw/bin/pre-commit" \
                    "$HOME/.nix-profile/bin/pre-commit"; do
            if [ -x "$cand" ]; then RUNNER_BIN="$cand"; return 0; fi
        done
    fi
    return 1
}

resolve_runner || {
    # A git-hooks.nix devShell may still install its runner shim below;
    # only fail closed when no install path can provide a runner.
    if ! [ -f "$REPO/flake.nix" ] \
        || ! grep -Eq 'git-hooks|pre-commit|prek' "$REPO/flake.nix" 2>/dev/null \
        || [ -f "$SHIM" ]; then
        printf 'hook dispatcher: %s not found; refusing to bypass hooks (use --no-verify)\n' "$RUNNER" >&2
        exit 1
    fi
}
run_hooks() {
    exec "$RUNNER_BIN" hook-impl --hook-type="$STAGE" --config=.pre-commit-config.yaml --hook-dir "$COMMON/hooks" -- "$@"
}

CONFIG="$REPO/.pre-commit-config.yaml"

# A git-hooks.nix devShell runs `pre-commit install` on every activation,
# and pre-commit's installer refuses while ANY core.hooksPath is visible -
# including the global one that delivers this dispatcher. When the repo is
# missing its config or shims, install them with the global scope masked:
# one devShell eval when the config is missing (the devShell symlinks the
# config and may install shims), otherwise a direct installer invocation.
# The repo-local override the devShell leaves behind is removed again so
# this dispatcher stays the hook entry point.
if [ -f "$REPO/flake.nix" ] \
    && grep -Eq 'git-hooks|pre-commit|prek' "$REPO/flake.nix" 2>/dev/null \
    && { [ ! -f "$CONFIG" ] || [ ! -f "$SHIM" ]; }; then
    if [ ! -f "$CONFIG" ]; then
        GIT_CONFIG_GLOBAL=/dev/null nix develop --no-update-lock-file -c true
        eval_status=$?
        if [ "$eval_status" -ne 0 ] && [ ! -f "$CONFIG" ]; then
            printf 'hook dispatcher: nix develop failed; blocking %s (bypass with --no-verify)\n' "$STAGE" >&2
            exit 1
        fi
        if [ "$eval_status" -ne 0 ]; then
            # Config exists now, so hooks below still run; a failed shim
            # install must not block the hook.
            printf 'hook dispatcher: devShell hook install failed; continuing\n' >&2
        fi
    fi
    # git-hooks.nix installs its own common-dir shims during the shellHook.
    # Remove the repo-local override so the activated global dispatcher stays
    # authoritative for subsequent commits in this checkout/worktree.
    git config --local --unset-all core.hooksPath 2>/dev/null || true
    if [ ! -f "$SHIM" ]; then
        # The devShell's shellHook only installs shims while it recreates
        # the config; with a converged config, install the shim directly.
        # Masked: the installer refuses while any core.hooksPath is visible.
        if command -v pre-commit >/dev/null 2>&1; then
            GIT_CONFIG_GLOBAL=/dev/null pre-commit install -c .pre-commit-config.yaml -t "$STAGE"
        elif command -v prek >/dev/null 2>&1; then
            GIT_CONFIG_GLOBAL=/dev/null prek install -c .pre-commit-config.yaml -t "$STAGE"
        else
            printf 'hook dispatcher: no pre-commit or prek installer on PATH; cannot install shims\n' >&2
        fi
        git config --local --unset-all core.hooksPath 2>/dev/null || true
    fi
    # The devShell may have (re)installed shims; re-detect the runner.
    if [ -f "$SHIM" ] && grep -Eq 'pre_commit|pre-commit' "$SHIM" 2>/dev/null \
        && ! grep -q 'generated by prek' "$SHIM" 2>/dev/null; then
        RUNNER="pre-commit"
    else
        RUNNER="prek"
    fi
    if ! resolve_runner; then
        if [ -x "$SHIM" ]; then
            # The shim embeds the store paths of the runner that installed
            # it; it runs without the runner on PATH.
            exec "$SHIM" "$@"
        fi
        printf 'hook dispatcher: %s not found; refusing to bypass hooks (use --no-verify)\n' "$RUNNER" >&2
        exit 1
    fi
    if [ -f "$CONFIG" ]; then
        run_hooks "$@"
    fi
    printf 'hook dispatcher: devShell declares no pre-commit hooks; skipping %s\n' "$STAGE" >&2
    exit 0
fi

if [ -f "$CONFIG" ]; then
    run_hooks "$@"
fi
if [ -f "$REPO/flake.nix" ]; then
    if [ -f "$SHIM" ] \
        && ! grep -q 'generated by prek' "$SHIM" 2>/dev/null \
        && ! grep -Eq 'pre_commit|pre-commit' "$SHIM" 2>/dev/null; then
        exec "$SHIM" "$@"
    fi
    printf 'hook dispatcher: devShell declares no pre-commit hooks; skipping %s\n' "$STAGE" >&2
    exit 0
fi

# Legacy fallback: repos with hand-installed hook scripts. Runner shims are
# excluded so we never double-dispatch through a dead shim.
if [ -f "$SHIM" ] \
    && ! grep -q 'generated by prek' "$SHIM" 2>/dev/null \
    && ! grep -Eq 'pre_commit|pre-commit' "$SHIM" 2>/dev/null; then
    exec "$SHIM" "$@"
fi

exit 0
