#!/bin/sh
# Global git hook dispatcher: makes prek hooks work in every worktree and
# fresh clone, regardless of which checkout generated the hook config.
#
# Stages: link or copy this script to pre-commit / pre-push; the stage is
# derived from the invoked name (home-manager's programs.git.hooks does this
# via its linkFarm).
#
# Policy:
#   - Repo with .pre-commit-config.yaml      -> run prek (fast path).
#   - Flake repo without it                  -> one `nix develop` eval so the
#     devShell's git-hooks.nix shellHook symlinks the config into THIS
#     worktree, then run prek directly (hook entries carry absolute store
#     paths, so the devShell env is not needed).
#   - Flake repo whose devShell declares no hooks -> skip loudly (exit 0).
#   - Failed nix develop eval (broken flake, network) -> FAIL CLOSED.
#   - Non-flake repo without config          -> honor a legacy hook script in
#     .git/hooks if one exists (prek shims excluded; a global core.hooksPath
#     would otherwise silently disable them).
#
# The only sanctioned bypass is `git commit|push --no-verify`.

unset PREK_ALLOW_NO_CONFIG

# git exports repo-targeting GIT_* variables to hooks (notably GIT_DIR and
# GIT_INDEX_FILE in linked worktrees). prek passes them through, and they
# hijack nested git operations in hook subprocesses (e.g. tests that commit
# in temp repos operate on THIS repo instead). Hooks run with cwd at the
# repo root, so these variables are redundant; drop them.
unset GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE GIT_OBJECT_DIRECTORY \
      GIT_ALTERNATE_OBJECT_DIRECTORIES GIT_COMMON_DIR GIT_GRAFT_FILE \
      GIT_CONFIG GIT_CONFIG_PARAMETERS GIT_QUARANTINE_PATH

STAGE="$(basename "$0")"

REPO="$(git rev-parse --show-toplevel 2>/dev/null)" || exit 0
cd "$REPO" || exit 1

PREK="${PREK_BIN:-prek}"
command -v "$PREK" >/dev/null 2>&1 || PREK="/etc/profiles/per-user/$(id -un)/bin/prek"
command -v "$PREK" >/dev/null 2>&1 || PREK="/run/current-system/sw/bin/prek"
command -v "$PREK" >/dev/null 2>&1 || PREK="$HOME/.nix-profile/bin/prek"
if ! command -v "$PREK" >/dev/null 2>&1; then
    printf 'hook dispatcher: prek not found; refusing to bypass hooks (use --no-verify)\n' >&2
    exit 1
fi

CONFIG="$REPO/.pre-commit-config.yaml"

if [ -f "$CONFIG" ]; then
    exec "$PREK" hook-impl --hook-type="$STAGE" --config=.pre-commit-config.yaml -- "$@"
fi

if [ -f "$REPO/flake.nix" ]; then
    if ! nix develop --no-update-lock-file -c true; then
        printf 'hook dispatcher: nix develop failed; blocking %s (bypass with --no-verify)\n' "$STAGE" >&2
        exit 1
    fi
    if [ -f "$CONFIG" ]; then
        exec "$PREK" hook-impl --hook-type="$STAGE" --config=.pre-commit-config.yaml -- "$@"
    fi
    printf 'hook dispatcher: devShell declares no pre-commit hooks; skipping %s\n' "$STAGE" >&2
    exit 0
fi

# Legacy fallback: repos with hand-installed hook scripts (not prek shims).
COMMON="$(git rev-parse --path-format=absolute --git-common-dir 2>/dev/null)" || exit 1
LEGACY="$COMMON/hooks/$STAGE"
if [ -f "$LEGACY" ] && ! grep -q 'generated by prek' "$LEGACY" 2>/dev/null; then
    exec "$LEGACY" "$@"
fi

exit 0
