services:
  api:
    volumes:
      - type: bind
        source: librechat.yaml
        target: /app/librechat.yaml
      - type: bind
        source: .env
        target: /app/.env
    # Allow the container to access the host machine's services
    extra_hosts:
      - "host.docker.internal:host-gateway"
