version: "3.4"

services:
  api:
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
      - type: bind
        source: ./.env
        target: /app/.env
