endpoint: https://bitgoinc.atlassian.net
user: ericcrosson@bitgo.com
project: VL
issuetype: Task
overrides:
  priority: Needs Triage
  assignee: ericcrosson@bitgo.com
  reporter: ericcrosson@bitgo.com
  initiative: DevOps Velocity
  # Numeric fields unsupported at this time
  # https://github.com/go-jira/jira/issues/379
  # story_points: 1
custom-commands:
  - name: mine
    help: display issues assigned to me
    script: |-
      if [ -n "$JIRA_PROJECT" ]; then
        # if `project: ...` configured just list the issues for current project
        {{jira}} list --query "resolution = unresolved and assignee=currentuser() and project = $JIRA_PROJECT ORDER BY priority asc, created"
      else
        # otherwise list issues for all projects
        {{jira}} list --query "resolution = unresolved and assignee=currentuser() ORDER BY priority asc, created"
      fi
  - name: sprint
    help: display issues in active sprint
    script: |-
      if [ -n "$JIRA_PROJECT" ]; then
        # if `project: ...` configured just list the issues for current project
        {{jira}} list --query "sprint in openSprints() and assignee=currentuser() and type != epic and resolution = unresolved and project=$JIRA_PROJECT ORDER BY rank asc, created"
      else
        # otherwise list issues for all projects
        {{jira}} list --query "sprint in openSprints() and assignee=currentuser() and type != epic and resolution = unresolved ORDER BY rank asc, created"
      fi
  - name: latest-bg-ticket
    help: display latest-created issue
    script: |-
      {{jira}} list --query "project = BitGo and created >= startOfDay() ORDER BY created DESC"
