endpoint: https://stratos-trade.atlassian.net
user: eric@stratos.trade
password-source: keyring
overrides:
  priority: Needs Triage
  assignee: eric@stratos.trade
  reporter: eric@stratos.trade
  issuetype: Task
custom-commands:
  - name: mine
    help: display issues assigned to me
    script: |-
      if [ -n "$JIRA_PROJECT" ]; then
        # if `project: ...` configured just list the issues for current project
        {{jira}} list --query "resolution = unresolved and assignee=currentuser() and project = $JIRA_PROJECT ORDER BY priority asc, created"
      else
        # otherwise list issues for all projects
        {{jira}} list --query "resolution = unresolved and assignee=currentuser() ORDER BY priority asc, created"
      fi
  - name: sprint
    help: display issues in active sprint
    script: |-
      if [ -n "$JIRA_PROJECT" ]; then
        # if `project: ...` configured just list the issues for current project
        {{jira}} list --query "sprint in openSprints() and assignee=currentuser() and type != epic and resolution = unresolved and project=$JIRA_PROJECT ORDER BY rank asc, created"
      else
        # otherwise list issues for all projects
        {{jira}} list --query "sprint in openSprints() and assignee=currentuser() and type != epic and resolution = unresolved ORDER BY rank asc, created"
      fi
