name: continuous-integration

on: pull_request

jobs:
  compile-helix:
    name: Compile Helix Editor
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Compile helix
        run: |
          cd helix
          cargo check
