---
name: Manually update nix flake input

on:
  workflow_dispatch:
    inputs:
      flake-input:
        description: The name of the flake input to update
        required: true
        type: string

jobs:
  update-flake-input:
    uses: ./.github/workflows/update-flake-input.yml
    with:
      flake-input: ${{ inputs.flake-input }}
    secrets:
      token: ${{ secrets.GH_TOKEN_PR }}
