---
name: Update nix flake inputs

on:
  workflow_dispatch: # allow manual triggering
  schedule:
    - cron: "0 8 * * *" # runs every day at 08:00 UTC

jobs:
  download-configuration:
    runs-on: ubuntu-latest
    outputs:
      flake-inputs: ${{ steps.download-configuration.outputs.flake-inputs }}
    steps:
      - id: download-configuration
        run: |
          : download auto-update configuration
          gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/EricCrosson/dotfiles/contents/.github/flake-inputs-to-auto-update.yaml \
          | jq --raw-output .content \
          | base64 -d \
          > flake-inputs-to-auto-update.yaml
          echo "flake-inputs=$(yq -c . flake-inputs-to-auto-update.yaml)" >> "$GITHUB_OUTPUT"

  invoke-update-flake-input-action:
    needs:
      - download-configuration
    strategy:
      matrix:
        flake-input: ${{ fromJSON(needs.download-configuration.outputs.flake-inputs) }}
    uses: ./.github/workflows/update-flake-input.yml
    with:
      flake-input: ${{ matrix.flake-input }}
